# Generated by Django 5.2 on 2025-04-25 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
